sudo: required
language: generic

services:
- docker

env:
  global:
    - DOCKER_IMAGE=numeconcopenhagen/jupyterlab-docker
    - GIT_LATEST_COMMIT=$(git rev-parse HEAD)
    - secure: "CgHbj4aEvmI6o4+9vIEdrsJlSf7ur4Rw0KqXQqciZNAKisNwZBIQaPITDEv0FY6y2/uQ4Kv3Hi1ekIgXKftwPkwgZ+w1TyLzuRs35ihRBxmdhdLJSHis1ov/r3HtYXQ0EiURgpIoO82QY/yJNO+2aToh9MfYGC309xUkzBvvzNFZrafRDzGN6/gDYs8bZx2FuDErs5qxVyxEcJe+21x3mU7/yq0at54odz1D6EzfE18XxtYGyOZAGBJmzBVi3x4GYBVOd4F/zkyCDrNIftREIqTje1VdpdEzLExnNf+oBo+3cYlQvPvYvkG46WJYwN9lt/Jq6/fH2BiGgqw1z6XK0nlfcIGnBukjSThYUt9nqpoxhOlCAM8LwCa7d9hf6cnN0CiBcB+k58GYUm4e8Lm/01UJPmSjJP1ECJ+GdCDadnZN8cbJnFeamrIN/RNBv5iHPx5h6OIwceo0fmLsk2WYYjUAQ6GWBRMlQMVBdlF2s3GkK6yvmxOo4drfhEB9MLmotJHF0RYVSTIth80F/xZjG6IM3Nna4xcoImekdGGR2SE2xRiUFQTGVT0fyQ8Mq0Fj5chEGwyDC1RioCMPaZK/Z/YJ1E+/s32gx8M3OOJY14K/uOjiEx9J5w3K09xf/mQyR/b/wBLaQ6KD7t1/kLgTaC096skG3p3vIvY7RoU4zrQ="
    - secure: "Dfw0wlUiZzU4ZLFFZCmi9M63W1JaGQ5moFMzgAe1OzeqdKiFi0z6pBv+JCCPh8owkAWxzmyhNvLZa2m9dy435NpMWGSdGCogZA5LhO2LGDDbj1b/HJAJ27ZzCEovxS4WR9K2Bsqdj77rahQNkhOhrBjGpThT6kQMuZYF7gRPJM27oB5CYUYhWYh8/ecuPQoIsbjeS4n3Akm8yciqIPME6SQPQtYD6fXCzdvtxYInY27o9bGU4lwa2ptm6Cwi1PY+JPFqPEsiVtITBKByLGhb+BaRFqySho0iNSiczE+mKncxWDjm07aNoEULofABjVGBvCQ0DL8KCX0J9D0Ap7uI28UpxtXaaEi/nDsPfHG7vTuiBwIYb3IhBiMEEjKMWMcGPrBXvULamclC4Fwyjqtk3wuFIBMBG0iAax79lsdevitPpv5bWFzHVY4Y3oqWKwV/MfVGUhPHuPbTGfeoXgvUyiGXgpK+eoROuQWEefqhG09pVEDNOLHFotrL/7zOYtqXRDGMT5lGPp7hwsbwdCIxhS4YKNTsLFLqkWp1Vk2VdDYvDDmL2cEt1vWln1Hzv+lr5LecnkvaTF5REzPtt/Nfk7w+3JBARC2YO1qitiQO3FMAqL8g4YV7f53JTnWecOYh2N12aHHuAOibCezG44FRQcS/js/Dx8GGaOPTIvDhX7k="

before_install:
  - bash .docker_setup.sh

script:
  - docker build -t $DOCKER_IMAGE:$GIT_LATEST_COMMIT .
  
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin;
      docker push $DOCKER_IMAGE;
    fi

notifications:
  email: false