name: base
channels:
- conda-forge
dependencies:
  - jupyter_conda
  - pip:
      - autopep8
      - black
      - yapf
      - jupyterlab_code_formatter
      - jupyterlab-git
      - jupyterlab_github
      - jupyterlab-solutions